rrt/min_nodes: 1500
system/bbx/r: 0.05 # radius of cylinder
system/bbx/overshoot: 0.5 #
tree/extension_range: 0.5

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-30.0, -30.0, -0.5]
boundary/max: [ 30.0,  30.0, 0.5]

# world_frame : "map"

