rrt/min_nodes: 1500
system/bbx/r: 0.1 # radius of cylinder
system/bbx/overshoot: 0.1 #
tree/extension_range: 0.5

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-30.0, -30.0, -1.0]
boundary/max: [ 30.0,  30.0, 1.0]

# world_frame : "map"

